# Generated by Django 4.0.6 on 2025-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0002_inventario_cantidad_inventario_detalles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('talla', models.CharField(max_length=3)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('precio_domicilio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField(help_text='AAAA-MM-DD')),
                ('hora', models.TimeField(help_text='HH:MM:SS')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valor_compra',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valor_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_compra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_venta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Camiseta'), (2, 'Pantalon'), (3, 'Gorra'), (4, 'Accesorio')], default=4),
        ),
        migrations.AddField(
            model_name='producto',
            name='gen',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateTimeField(default='2025-01-02', help_text='AAAA-MM-DD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Empleado'), (3, 'Cliente'), (4, 'Proveedor')], default=4),
        ),
    ]
