# Generated by Django 4.0.6 on 2025-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0003_carrito_factura_remove_inventario_valor_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
