# Generated by Django 4.0.6 on 2025-02-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0004_alter_usuario_apellido_2_alter_usuario_nombre_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha_pago', models.IntegerField()),
                ('comisiones', models.CharField(blank=True, max_length=100, null=True)),
                ('prestaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_extra', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='hora',
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(help_text='AAAA-MM-DD'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(max_length=100)),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenoneseven.salario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenoneseven.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenoneseven.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenoneseven.producto')),
            ],
        ),
    ]
