# Generated by Django 4.0.6 on 2025-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0005_salario_remove_factura_hora_alter_producto_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateTimeField(help_text='AAAA-MM-DD'),
        ),
    ]
