# Generated by Django 4.0.6 on 2025-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0006_remove_carrito_total_alter_usuario_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(help_text='AAAA-MM-DD'),
        ),
    ]
