# Generated by Django 4.0.6 on 2025-03-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevenoneseven', '0007_alter_usuario_fecha_nac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido_1',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_1',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='detallecompras',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallecompras',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='precio_domicilio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_2',
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='precioProducto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sevenoneseven.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_factura_cliente', to='sevenoneseven.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='empleado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_factura_empleado', to='sevenoneseven.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='medioPago',
            field=models.IntegerField(choices=[(1, 'PSE'), (2, 'Tarjeta Credito'), (3, 'Tarjeta Debito'), (4, 'Efecty')], default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='gen',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Camiseta'), (2, 'Pantalon'), (3, 'Gorra'), (4, 'Accesorio'), (5, 'Polo')], default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(help_text='DD-MM-AAAA'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Empleado'), (3, 'Cliente')], default=3),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Salario',
        ),
    ]
